--- ../Makefile	2020-09-20 09:52:42.000000000 -0700
+++ ../Makefile.patched	2020-09-20 10:01:41.000000000 -0700
@@ -19,16 +19,6 @@
 endif

 CT_APPS := emqx \
-           emqx_auth_clientid \
-           emqx_auth_http \
-           emqx_auth_jwt \
-           emqx_auth_ldap \
-           emqx_auth_mongo \
-           emqx_auth_mysql \
-           emqx_auth_pgsql \
-           emqx_auth_redis \
-           emqx_auth_username \
-           emqx_auth_mnesia \
            emqx_sasl \
            emqx_coap \
            emqx_recon \
@@ -45,7 +35,7 @@
            emqx_bridge_mqtt \
            emqx_rule_engine \
            emqx_extension_hook \
-           emqx_exproto
+					 emqx_cassandra_backend

 .PHONY: default
 default: $(REBAR) $(PROFILE)
