--- ../Makefile	2020-02-20 15:13:46.000000000 -0800
+++ Makefile	2020-02-20 15:23:15.000000000 -0800
@@ -25,12 +25,9 @@
 PROFILES := emqx emqx-edge
 PKG_PROFILES := emqx-pkg emqx-edge-pkg

-CT_APPS := emqx_auth_jwt emqx_auth_mysql emqx_auth_username \
-		emqx_delayed_publish emqx_management emqx_recon emqx_rule_enginex \
-		emqx_stomp emqx_auth_clientid  emqx_auth_ldap   emqx_auth_pgsql \
-		emqx_coap emqx_lua_hook emqx_passwd emqx_reloader emqx_sn \
-		emqx_web_hook emqx_auth_http emqx_auth_mongo emqx_auth_redis \
-		emqx_dashboard emqx_lwm2m emqx_psk_file emqx_retainer emqx_statsd
+CT_APPS :=   emqx_delayed_publish emqx_management emqx_recon emqx_rule_enginex \
+		emqx_stomp emqx_passwd emqx_reloader \
+		emqx_web_hook emqx_dashboard emqx_retainer emqx_statsd emqx_cassandra_backend

 .PHONY: default
 default: $(REBAR) $(PROFILE)
