{application,emqx_cassandra_backend,
             [{description,"EMQ X Cassandra backend for authentication and logging"},
              {vsn,"0.0.0+build.4.refdee4dd4"},
              {modules,[cassandra_cli,emqx_acl_cassandra,emqx_auth_cassandra,
                        emqx_auth_cassandra_cli,emqx_cassandra_backend,
                        emqx_cassandra_backend_app,emqx_cassandra_backend_cfg,
                        emqx_cassandra_backend_sup]},
              {registered,[emqx_cassandra_backend_sup]},
              {applications,[kernel,stdlib,clique,emqx_passwd,lager]},
              {mod,{emqx_cassandra_backend_app,[]}},
              {env,[]},
              {licenses,["Apache-2.0"]},
              {links,["Github",
                      "https://github.com/babakyadegari/emqx-cassandra_backend"]}]}.
